export const SUCCESS = 'SUCCESS';
export const FAIL = 'FAIL';

export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_LIST_UPDATE = 'PRODUCT_LIST_UPDATE';

export const COMPANIES_SUCCESS = 'COMPANIES_SUCCESS';
export const COMPANIES_FAIL = 'COMPANIES_FAIL';

export const TAGS_SUCCESS = 'TAGS_SUCCESS';

export const TYPES_SUCCESS = 'TYPES_SUCCESS';

export const BASKET_CREATE = 'BASKET_CREATE';
export const BASKET_INCREASE = 'BASKET_INCREASE';
export const BASKET_DECREASE = 'BASKET_DECREASE';
export const BASKET_TOTAL_PRICE_UPDATE = 'BASKET_TOTAL_PRICE_UPDATE';
export const BASKET_DELETE = 'BASKET_DELETE';

export const MOBILE_BASKET = 'MOBILE_BASKET';
export const MOBILE_FILTER = 'MOBILE_FILTER';
