export const SUCCESS = 'SUCCESS';
export const FAIL = 'FAIL';
export const LOADING = 'LOADING';

export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_LIST_LOADING = 'PRODUCT_LIST_LOADING';

export const COMPANIES_SUCCESS = 'COMPANIES_SUCCESS';
export const COMPANIES_FAIL = 'COMPANIES_FAIL';
export const COMPANIES_LOADING = 'COMPANIES_LOADING';

export const TAGS_SUCCESS = 'TAGS_SUCCESS';
